In [4]:
import geopandas
import pandas as pd

In [11]:
oas = geopandas.read_file('output_areas.shp')

In [12]:
oas

,oa_id,Join_Count,pop,pop_den,road_den,SUM_Shape_,inter_den,sum,H,poi_den,Shape_Leng,Shape_Area,Predicted,ln_popden,price_k,geometry
0,0,17,3488,5023,8.500442,1.0,24.48,2,0.00,2.88,0.025095,0.000035,11052.279987,8.521783,11.052280,"POLYGON Z ((104.20479 30.66667 0.00000, 104.20..."
1,1,4,536,772,3.726961,1.0,5.76,2,0.00,2.88,0.033333,0.000069,11983.404602,6.648985,11.983405,None
2,2,8,1024,1475,6.506793,1.0,11.52,7,1.15,10.08,0.033333,0.000069,13625.805686,7.296413,13.625806,None
3,3,24,1486,2140,16.507081,1.0,34.56,184,1.82,264.96,0.022667,0.000022,9213.950356,7.668561,9.213950,None
4,4,3,2319,3339,5.091071,1.0,4.32,5,1.33,7.20,0.006612,0.000002,13233.969831,8.113427,13.233970,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,746,22,602,867,9.124699,1.0,31.68,13,0.83,18.72,0.033333,0.000069,11796.066439,6.765039,11.796066,None
747,747,21,6537,9413,8.847477,1.0,30.24,18,1.72,25.92,0.033333,0.000069,25567.457944,9.149847,25.567458,None
748,748,20,569,819,7.061171,1.0,28.80,15,1.40,21.60,0.033333,0.000069,12002.165978,6.708084,12.002166,None
749,749,15,2730,3931,7.732232,1.0,21.60,34,1.50,48.96,0.033333,0.000069,10534.842208,8.276649,10.534842,None
750,750,25,771,1110,17.679137,1.0,36.00,3,1.10,4.32,0.031522,0.000062,11246.207600,7.012115,11.246208,None

In [14]:
oas.columns

Index(['oa_id', 'Join_Count', 'pop', 'pop_den', 'road_den', 'SUM_Shape_',
       'inter_den', 'sum', 'H', 'poi_den', 'Shape_Leng', 'Shape_Area',
       'Predicted', 'ln_popden', 'price_k', 'geometry'],
      dtype='object')

In [15]:
oas = oas.rename(columns={"oa_id":"GEOID"})

In [18]:
oas

,GEOID,Join_Count,pop,pop_den,road_den,SUM_Shape_,inter_den,sum,H,poi_den,Shape_Leng,Shape_Area,Predicted,ln_popden,price_k,geometry
0,0,17,3488,5023,8.500442,1.0,24.48,2,0.00,2.88,0.025095,0.000035,11052.279987,8.521783,11.052280,"POLYGON Z ((104.20479 30.66667 0.00000, 104.20..."
1,1,4,536,772,3.726961,1.0,5.76,2,0.00,2.88,0.033333,0.000069,11983.404602,6.648985,11.983405,None
2,2,8,1024,1475,6.506793,1.0,11.52,7,1.15,10.08,0.033333,0.000069,13625.805686,7.296413,13.625806,None
3,3,24,1486,2140,16.507081,1.0,34.56,184,1.82,264.96,0.022667,0.000022,9213.950356,7.668561,9.213950,None
4,4,3,2319,3339,5.091071,1.0,4.32,5,1.33,7.20,0.006612,0.000002,13233.969831,8.113427,13.233970,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,746,22,602,867,9.124699,1.0,31.68,13,0.83,18.72,0.033333,0.000069,11796.066439,6.765039,11.796066,None
747,747,21,6537,9413,8.847477,1.0,30.24,18,1.72,25.92,0.033333,0.000069,25567.457944,9.149847,25.567458,None
748,748,20,569,819,7.061171,1.0,28.80,15,1.40,21.60,0.033333,0.000069,12002.165978,6.708084,12.002166,None
749,749,15,2730,3931,7.732232,1.0,21.60,34,1.50,48.96,0.033333,0.000069,10534.842208,8.276649,10.534842,None
750,750,25,771,1110,17.679137,1.0,36.00,3,1.10,4.32,0.031522,0.000062,11246.207600,7.012115,11.246208,None

In [19]:
oas2 = geopandas.read_file('output_areas.shp')

In [20]:
oas2

,GEOID,Join_Count,pop,pop_den,road_den,SUM_Shape_,inter_den,sum,H,poi_den,Shape_Leng,Shape_Area,Predicted,ln_popden,price_k,geometry
0,0,17,3488,5023,8.500442,1.0,24.48,2,0.00,2.88,0.025095,0.000035,11052.279987,8.521783,11.052280,"POLYGON Z ((104.20479 30.66667 0.00000, 104.20..."
1,1,4,536,772,3.726961,1.0,5.76,2,0.00,2.88,0.033333,0.000069,11983.404602,6.648985,11.983405,None
2,2,8,1024,1475,6.506793,1.0,11.52,7,1.15,10.08,0.033333,0.000069,13625.805686,7.296413,13.625806,None
3,3,24,1486,2140,16.507081,1.0,34.56,184,1.82,264.96,0.022667,0.000022,9213.950356,7.668561,9.213950,None
4,4,3,2319,3339,5.091071,1.0,4.32,5,1.33,7.20,0.006612,0.000002,13233.969831,8.113427,13.233970,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,746,22,602,867,9.124699,1.0,31.68,13,0.83,18.72,0.033333,0.000069,11796.066439,6.765039,11.796066,None
747,747,21,6537,9413,8.847477,1.0,30.24,18,1.72,25.92,0.033333,0.000069,25567.457944,9.149847,25.567458,None
748,748,20,569,819,7.061171,1.0,28.80,15,1.40,21.60,0.033333,0.000069,12002.165978,6.708084,12.002166,None
749,749,15,2730,3931,7.732232,1.0,21.60,34,1.50,48.96,0.033333,0.000069,10534.842208,8.276649,10.534842,None
750,750,25,771,1110,17.679137,1.0,36.00,3,1.10,4.32,0.031522,0.000062,11246.207600,7.012115,11.246208,None

In [4]:
tes = geopandas.read_file('tessellation.shp')
tes

      tile_ID                                           geometry
0           0  POLYGON ((73.49973 38.79265, 73.49973 38.96748...
1           1  POLYGON ((73.49973 38.96748, 73.49973 39.14187...
2           2  POLYGON ((73.49973 39.14187, 73.49973 39.31584...
3           3  POLYGON ((73.49973 39.31584, 73.49973 39.48937...
4           4  POLYGON ((73.72431 38.44171, 73.72431 38.61740...
...       ...                                                ...
25509   25509  POLYGON ((134.58517 47.75997, 134.58517 47.910...
25510   25510  POLYGON ((134.58517 47.91072, 134.58517 48.061...
25511   25511  POLYGON ((134.58517 48.06103, 134.58517 48.210...
25512   25512  POLYGON ((134.58517 48.21091, 134.58517 48.360...
25513   25513  POLYGON ((134.58517 48.36035, 134.58517 48.509...

[25514 rows x 2 columns]

In [15]:
tes.columns

Index(['tile_ID', 'geometry'], dtype='object')

In [16]:
oas = geopandas.read_file('/Users/chizhang/Desktop/didi/data/didi_cd/output_areas.shp')

DriverError: '/Users/chizhang/Desktop/didi/data/didi_cd/output_areas.shp' not recognized as a supported file format.